server:
  port: 8085

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ahhh;encrypt=true;trustServerCertificate=true
    username: sa
    password: Admin12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
